"""
Generate docs/coverage.md from the current DBC corpus.

Phase 5 stub: produces a basic Markdown coverage matrix.
Phase 9+11 will enrich this with cross-DBC source attribution and per-PGN signal counts.

Usage:
  python -m opendbc_ag.tools.coverage_report [--repo-root PATH]
"""
from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    repo = args.repo_root

    from opendbc_ag.tools._dbc_utils import first_matrix

    dbc_dir = repo / "opendbc_ag/dbc"
    if not dbc_dir.exists():
        raise SystemExit(f"No DBC dir at {dbc_dir}")

    per_dbc = []
    total_frames = 0
    total_signals = 0
    pgn_id_set: set[int] = set()
    for dbc_path in sorted(dbc_dir.glob("*.dbc")):
        mat = first_matrix(dbc_path)
        n_frames = len(mat.frames)
        n_signals = sum(len(f.signals) for f in mat.frames)
        per_dbc.append((dbc_path.name, n_frames, n_signals))
        total_frames += n_frames
        total_signals += n_signals
        for f in mat.frames:
            pgn_id_set.add(f.arbitration_id.id)

    lines = [
        "# Coverage matrix",
        "",
        f"_Auto-generated by `opendbc_ag/tools/coverage_report.py`. Do not hand-edit._",
        "",
        f"**Total unique PGN IDs:** {len(pgn_id_set)}",
        f"**Total frames:** {total_frames}",
        f"**Total signals:** {total_signals}",
        "",
        "## Per-DBC breakdown",
        "",
        "| DBC file | Frames | Signals |",
        "|---|---|---|",
    ]
    for name, frames, signals in per_dbc:
        lines.append(f"| `{name}` | {frames} | {signals} |")
    lines += [
        f"| **Total** | **{total_frames}** | **{total_signals}** |",
        "",
        "## Source attribution",
        "",
        "- `iso11783_from_agisostack.dbc` — extracted from [AgIsoStack++](https://github.com/Open-Agriculture/AgIsoStack-plus-plus) (MIT). Includes signal-level definitions for speed/distance, guidance, time/date, language, maintain-power, heartbeat. **Bus speed: 250 kbps (ISOBUS implement bus).**",
        "- `iso11783_from_vdma.dbc` — scraped from [isobus.net VDMA Data Dictionary](https://www.isobus.net/isobus/) (public summaries). PGN-level only; each frame has a `RawPayload` placeholder + detail-page URL in comment for community PR-driven signal enrichment. **Bus speed: 250 kbps (ISOBUS implement bus).**",
        "- `j1939_ag_subset.dbc` — hand-curated SAE J1939 ag-relevant subset with signal-level definitions from Wikipedia + CSS Electronics free educational posts + iDoka/awesome-automotive-can-id. No paywalled SAE PDF content. **Bus speed: 500 kbps (J1939 chassis bus).**",
        "",
        "_Note: DBC `BS_:` line is empty per cantools-compatibility convention; bus speed is documented here and read by consumers via the `BA_ \"Baudrate\"` attribute mechanism if needed._",
        "",
        "## Scope policy",
        "",
        "Pure-standard PGNs only. CI rejects any PGN ID in proprietary ranges (`0xEF00` / `0x1EF00` / `0xFF00..0xFFFF` / `0x1FF00..0x1FFFF`) AND any frame whose name matches `^(Proprietary|Reserved)`. Predicate lives in `opendbc_ag/tools/_scope_policy.py`.",
        "",
    ]

    docs = repo / "docs"
    docs.mkdir(exist_ok=True)
    out = docs / "coverage.md"
    out.write_text("\n".join(lines))
    print(f"Wrote: {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
